; generated by PrusaSlicer 2.2.0+ on 2020-05-18 at 01:48:30 UTC

; 

; external perimeters extrusion width = 0.45mm
; perimeters extrusion width = 0.45mm
; infill extrusion width = 0.45mm
; solid infill extrusion width = 0.45mm
; top infill extrusion width = 0.40mm
; first layer extrusion width = 0.42mm

M73 P0 R2
M73 Q0 S2
M201 X1000 Y1000 Z1000 E5000 ; sets maximum accelerations, mm/sec^2
M203 X200 Y200 Z12 E120 ; sets maximum feedrates, mm/sec
M204 P1250 R1250 T1250 ; sets acceleration (P, T) and retract acceleration (R), mm/sec^2
M205 X8.00 Y8.00 Z0.40 E4.50 ; sets the jerk limits, mm/sec
M205 S0 T0 ; sets the minimum extruding and travel feed rate, mm/sec
M107
M862.3 P "MK3S" ; printer model check
M862.1 P0.4 ; nozzle diameter check
M115 U3.8.1 ; tell printer latest fw version
G90 ; use absolute coordinates
M83 ; extruder relative mode
M104 S215 ; set extruder temp
M140 S60 ; set bed temp
M190 S60 ; wait for bed temp
M109 S215 ; wait for extruder temp
G28 W ; home all without mesh bed level
G80 ; mesh bed leveling
G1 Y-3.0 F1000.0 ; go outside print area
G92 E0.0
G1 X60.0 E9.0 F1000.0 ; intro line
M73 Q2 S2
M73 P2 R2
G1 X100.0 E12.5 F1000.0 ; intro line
G92 E0.0
M221 S95
G21 ; set units to millimeters
G90 ; use absolute coordinates
M83 ; use relative distances for extrusion
M900 K30 ; Filament gcode
;BEFORE_LAYER_CHANGE
G92 E0.0
;0.2


G1 E-0.80000 F2100.00000
G1 Z0.600 F10800.000
;AFTER_LAYER_CHANGE
;0.2
G1 X9.793 Y84.164
G1 Z0.200
G1 E0.80000 F2100.00000
M204 S1000
G1 F1200.000
G1 X10.712 Y83.954 E0.02954
G1 X40.774 Y83.954 E0.94257
G1 X41.655 Y84.124 E0.02813
G1 X42.407 Y84.607 E0.02802
G1 X42.929 Y85.336 E0.02813
G1 X43.144 Y86.208 E0.02813
G1 X43.147 Y116.376 E0.94592
G1 X42.973 Y117.222 E0.02708
G1 X42.512 Y117.948 E0.02696
G1 X41.726 Y118.507 E0.03024
G1 X40.779 Y118.708 E0.03036
G1 X10.721 Y118.707 E0.94245
G1 X9.878 Y118.534 E0.02696
G1 X9.153 Y118.073 E0.02696
G1 X8.592 Y117.283 E0.03036
G1 X8.393 Y116.339 E0.03024
G1 X8.393 Y86.281 E0.94245
G1 X8.567 Y85.439 E0.02696
G1 X9.028 Y84.713 E0.02696
G1 X9.744 Y84.199 E0.02766
G1 F8640.000
G1 X10.712 Y83.954 E-0.23038
G1 X13.006 Y83.954 E-0.52962
G1 E-0.04000 F2100.00000
G1 Z0.800 F10800.000
G1 X11.557 Y87.118
G1 Z0.200
G1 E0.80000 F2100.00000
G1 F1200.000
G1 X39.983 Y87.118 E0.89127
G1 X39.983 Y115.544 E0.89127
G1 X11.557 Y115.544 E0.89127
G1 X11.557 Y87.178 E0.88939
G1 X11.180 Y86.741 F10800.000
G1 F1200.000
G1 X40.360 Y86.741 E0.91492
G1 X40.360 Y115.921 E0.91492
G1 X11.180 Y115.921 E0.91492
G1 X11.180 Y86.801 E0.91304
G1 X11.566 Y86.844 F10800.000
G1 F8640.000
G1 X14.471 Y86.794 E-0.76000
G1 E-0.04000 F2100.00000
G1 Z0.800 F10800.000
G1 X39.870 Y88.000
G1 Z0.200
G1 E0.80000 F2100.00000
G1 F1200.000
G1 X39.270 Y87.401 E0.02681
G1 X38.732 Y87.401 E0.01701
G1 X39.700 Y88.368 E0.04327
G1 X39.700 Y88.906 E0.01701
G1 X38.195 Y87.401 E0.06733
G1 X37.657 Y87.401 E0.01701
G1 X39.700 Y89.444 E0.09138
G1 X39.700 Y89.982 E0.01701
G1 X37.119 Y87.401 E0.11544
G1 X36.581 Y87.401 E0.01701
G1 X39.700 Y90.520 E0.13949
G1 X39.700 Y91.057 E0.01701
G1 X36.043 Y87.401 E0.16355
G1 X35.505 Y87.401 E0.01701
G1 X39.700 Y91.595 E0.18760
G1 X39.700 Y92.133 E0.01701
G1 X34.968 Y87.401 E0.21165
G1 X34.430 Y87.401 E0.01701
G1 X39.700 Y92.671 E0.23571
G1 X39.700 Y93.209 E0.01701
G1 X33.892 Y87.401 E0.25976
G1 X33.354 Y87.401 E0.01701
G1 X39.700 Y93.747 E0.28382
G1 X39.700 Y94.285 E0.01701
G1 X32.816 Y87.401 E0.30787
G1 X32.278 Y87.401 E0.01701
G1 X39.700 Y94.822 E0.33192
G1 X39.700 Y95.360 E0.01701
G1 X31.740 Y87.401 E0.35598
G1 X31.203 Y87.401 E0.01701
G1 X39.700 Y95.898 E0.38003
G1 X39.700 Y96.436 E0.01701
G1 X30.665 Y87.401 E0.40409
G1 X30.127 Y87.401 E0.01701
G1 X39.700 Y96.974 E0.42814
G1 X39.700 Y97.512 E0.01701
G1 X29.589 Y87.401 E0.45220
G1 X29.051 Y87.401 E0.01701
G1 X39.700 Y98.049 E0.47625
G1 X39.700 Y98.587 E0.01701
G1 X28.513 Y87.401 E0.50030
G1 X27.975 Y87.401 E0.01701
G1 X39.700 Y99.125 E0.52436
G1 X39.700 Y99.663 E0.01701
G1 X27.438 Y87.401 E0.54841
G1 X26.900 Y87.401 E0.01701
G1 X39.700 Y100.201 E0.57247
G1 X39.700 Y100.739 E0.01701
G1 X26.362 Y87.401 E0.59652
G1 X25.824 Y87.401 E0.01701
G1 X39.700 Y101.277 E0.62057
G1 X39.700 Y101.814 E0.01701
G1 X25.286 Y87.401 E0.64463
G1 X24.748 Y87.401 E0.01701
G1 X39.700 Y102.352 E0.66868
G1 X39.700 Y102.890 E0.01701
G1 X24.210 Y87.401 E0.69274
G1 X23.673 Y87.401 E0.01701
G1 X39.700 Y103.428 E0.71679
G1 X39.700 Y103.966 E0.01701
G1 X23.135 Y87.401 E0.74085
G1 X22.597 Y87.401 E0.01701
G1 X39.700 Y104.504 E0.76490
G1 X39.700 Y105.042 E0.01701
G1 X22.059 Y87.401 E0.78895
G1 X21.521 Y87.401 E0.01701
G1 X39.700 Y105.579 E0.81301
G1 X39.700 Y106.117 E0.01701
G1 X20.983 Y87.401 E0.83706
G1 X20.446 Y87.401 E0.01701
G1 X39.700 Y106.655 E0.86112
G1 X39.700 Y107.193 E0.01701
G1 X19.908 Y87.401 E0.88517
G1 X19.370 Y87.401 E0.01701
G1 X39.700 Y107.731 E0.90922
G1 X39.700 Y108.269 E0.01701
G1 X18.832 Y87.401 E0.93328
G1 X18.294 Y87.401 E0.01701
G1 X39.700 Y108.807 E0.95733
G1 X39.700 Y109.344 E0.01701
G1 X17.756 Y87.401 E0.98139
G1 X17.218 Y87.401 E0.01701
G1 X39.700 Y109.882 E1.00544
G1 X39.700 Y110.420 E0.01701
G1 X16.681 Y87.401 E1.02950
M73 Q46 S1
M73 P46 R1
G1 X16.143 Y87.401 E0.01701
G1 X39.700 Y110.958 E1.05355
G1 X39.700 Y111.496 E0.01701
G1 X15.605 Y87.401 E1.07760
G1 X15.067 Y87.401 E0.01701
G1 X39.700 Y112.034 E1.10166
G1 X39.700 Y112.572 E0.01701
G1 X14.529 Y87.401 E1.12571
G1 X13.991 Y87.401 E0.01701
G1 X39.700 Y113.109 E1.14977
G1 X39.700 Y113.647 E0.01701
G1 X13.453 Y87.401 E1.17382
G1 X12.916 Y87.401 E0.01701
G1 X39.700 Y114.185 E1.19787
G1 X39.700 Y114.723 E0.01701
G1 X12.378 Y87.401 E1.22193
G1 X11.840 Y87.401 E0.01701
G1 X39.700 Y115.261 E1.24598
G1 X39.162 Y115.261 E0.01701
G1 X11.840 Y87.938 E1.22193
G1 X11.840 Y88.476 E0.01701
G1 X38.624 Y115.261 E1.19787
G1 X38.087 Y115.261 E0.01701
G1 X11.840 Y89.014 E1.17382
G1 X11.840 Y89.552 E0.01701
G1 X37.549 Y115.261 E1.14976
G1 X37.011 Y115.261 E0.01701
G1 X11.840 Y90.090 E1.12571
G1 X11.840 Y90.628 E0.01701
G1 X36.473 Y115.261 E1.10166
G1 X35.935 Y115.261 E0.01701
G1 X11.840 Y91.166 E1.07760
G1 X11.840 Y91.703 E0.01701
G1 X35.397 Y115.261 E1.05355
G1 X34.859 Y115.261 E0.01701
G1 X11.840 Y92.241 E1.02949
G1 X11.840 Y92.779 E0.01701
G1 X34.322 Y115.261 E1.00544
G1 X33.784 Y115.261 E0.01701
G1 X11.840 Y93.317 E0.98139
G1 X11.840 Y93.855 E0.01701
G1 X33.246 Y115.261 E0.95733
G1 X32.708 Y115.261 E0.01701
G1 X11.840 Y94.393 E0.93328
G1 X11.840 Y94.930 E0.01701
G1 X32.170 Y115.261 E0.90922
G1 X31.632 Y115.261 E0.01701
G1 X11.840 Y95.468 E0.88517
G1 X11.840 Y96.006 E0.01701
G1 X31.094 Y115.261 E0.86112
G1 X30.557 Y115.261 E0.01701
G1 X11.840 Y96.544 E0.83706
G1 X11.840 Y97.082 E0.01701
G1 X30.019 Y115.261 E0.81301
G1 X29.481 Y115.261 E0.01701
G1 X11.840 Y97.620 E0.78895
G1 X11.840 Y98.158 E0.01701
G1 X28.943 Y115.261 E0.76490
G1 X28.405 Y115.261 E0.01701
G1 X11.840 Y98.695 E0.74084
G1 X11.840 Y99.233 E0.01701
G1 X27.867 Y115.261 E0.71679
G1 X27.330 Y115.261 E0.01701
G1 X11.840 Y99.771 E0.69274
G1 X11.840 Y100.309 E0.01701
G1 X26.792 Y115.261 E0.66868
G1 X26.254 Y115.261 E0.01701
G1 X11.840 Y100.847 E0.64463
G1 X11.840 Y101.385 E0.01701
G1 X25.716 Y115.261 E0.62057
G1 X25.178 Y115.261 E0.01701
G1 X11.840 Y101.923 E0.59652
G1 X11.840 Y102.460 E0.01701
G1 X24.640 Y115.261 E0.57247
G1 X24.102 Y115.261 E0.01701
G1 X11.840 Y102.998 E0.54841
G1 X11.840 Y103.536 E0.01701
G1 X23.565 Y115.261 E0.52436
G1 X23.027 Y115.261 E0.01701
G1 X11.840 Y104.074 E0.50030
M73 Q90 S0
M73 P90 R0
G1 X11.840 Y104.612 E0.01701
G1 X22.489 Y115.261 E0.47625
G1 X21.951 Y115.261 E0.01701
G1 X11.840 Y105.150 E0.45219
G1 X11.840 Y105.688 E0.01701
G1 X21.413 Y115.261 E0.42814
G1 X20.875 Y115.261 E0.01701
G1 X11.840 Y106.225 E0.40409
G1 X11.840 Y106.763 E0.01701
G1 X20.337 Y115.261 E0.38003
G1 X19.800 Y115.261 E0.01701
G1 X11.840 Y107.301 E0.35598
G1 X11.840 Y107.839 E0.01701
G1 X19.262 Y115.261 E0.33192
G1 X18.724 Y115.261 E0.01701
G1 X11.840 Y108.377 E0.30787
G1 X11.840 Y108.915 E0.01701
G1 X18.186 Y115.261 E0.28382
G1 X17.648 Y115.261 E0.01701
G1 X11.840 Y109.452 E0.25976
G1 X11.840 Y109.990 E0.01701
G1 X17.110 Y115.261 E0.23571
G1 X16.572 Y115.261 E0.01701
G1 X11.840 Y110.528 E0.21165
G1 X11.840 Y111.066 E0.01701
G1 X16.035 Y115.261 E0.18760
G1 X15.497 Y115.261 E0.01701
G1 X11.840 Y111.604 E0.16354
G1 X11.840 Y112.142 E0.01701
G1 X14.959 Y115.261 E0.13949
G1 X14.421 Y115.261 E0.01701
G1 X11.840 Y112.680 E0.11544
G1 X11.840 Y113.217 E0.01701
G1 X13.883 Y115.261 E0.09138
G1 X13.345 Y115.261 E0.01701
G1 X11.840 Y113.755 E0.06733
G1 X11.840 Y114.293 E0.01701
G1 X12.808 Y115.261 E0.04327
G1 X12.270 Y115.261 E0.01701
G1 X11.670 Y114.661 E0.02681
G1 F8640.000;_WIPE
G1 X12.270 Y115.261 E-0.19575
G1 F8640.000;_WIPE
G1 X12.808 Y115.261 E-0.12419
G1 F8640.000;_WIPE
G1 X11.840 Y114.293 E-0.31597
G1 F8640.000;_WIPE
G1 X11.840 Y113.756 E-0.12409
G1 E-0.04000 F2100.00000
G1 Z0.800 F10800.000
; Filament-specific end gcode
G4 ; wait
M221 S100
M104 S0 ; turn off temperature
M140 S0 ; turn off heatbed
M107 ; turn off fan
G1 Z30.8 ; Move print head up
G1 X0 Y200 F3000 ; home X axis
M84 ; disable motors
M73 P100 R0
M73 Q100 S0
; filament used [mm] = 77.7
; filament used [cm3] = 0.2
; filament used [g] = 0.2
; filament cost = 0.0

; total filament used [g] = 0.2
; total filament cost = 0.0
; estimated printing time (normal mode) = 2m 17s
; estimated printing time (silent mode) = 2m 17s

; avoid_crossing_perimeters = 0
; bed_custom_model = 
; bed_custom_texture = 
; bed_shape = 0x0,250x0,250x210,0x210
; bed_temperature = 60
; before_layer_gcode = ;BEFORE_LAYER_CHANGE\nG92 E0.0\n;[layer_z]\n\n
; between_objects_gcode = 
; bottom_fill_pattern = rectilinear
; bottom_solid_layers = 4
; bottom_solid_min_thickness = 0.5
; bridge_acceleration = 1000
; bridge_angle = 0
; bridge_fan_speed = 100
; bridge_flow_ratio = 0.95
; bridge_speed = 30
; brim_width = 0
; clip_multipart_objects = 1
; compatible_printers_condition_cummulative = "printer_notes=~/.*PRINTER_VENDOR_PRUSA3D.*/ and printer_notes=~/.*PRINTER_MODEL_MK3.*/ and nozzle_diameter[0]==0.4";"! (printer_notes=~/.*PRINTER_VENDOR_PRUSA3D.*/ and printer_notes=~/.*PRINTER_MODEL_MK(2.5|3).*/ and single_extruder_multi_material)"
; complete_objects = 0
; cooling = 1
; cooling_tube_length = 5
; cooling_tube_retraction = 91.5
; default_acceleration = 1000
; default_filament_profile = "Prusament PLA"
; default_print_profile = 0.15mm QUALITY @MK3
; deretract_speed = 0
; disable_fan_first_layers = 1
; dont_support_bridges = 1
; draft_shield = 0
; duplicate_distance = 6
; elefant_foot_compensation = 0.2
; end_filament_gcode = "; Filament-specific end gcode"
; end_gcode = G4 ; wait\nM221 S100\nM104 S0 ; turn off temperature\nM140 S0 ; turn off heatbed\nM107 ; turn off fan\n{if layer_z < max_print_height}G1 Z{z_offset+min(layer_z+30, max_print_height)}{endif} ; Move print head up\nG1 X0 Y200 F3000 ; home X axis\nM84 ; disable motors
; ensure_vertical_shell_thickness = 1
; external_perimeter_extrusion_width = 0.45
; external_perimeter_speed = 25
; external_perimeters_first = 0
; extra_loading_move = -2
; extra_perimeters = 0
; extruder_clearance_height = 20
; extruder_clearance_radius = 45
; extruder_colour = ""
; extruder_offset = 0x0
; extrusion_axis = E
; extrusion_multiplier = 1
; extrusion_width = 0.45
; fan_always_on = 1
; fan_below_layer_time = 100
; filament_colour = #FF8000
; filament_cooling_final_speed = 3.4
; filament_cooling_initial_speed = 2.2
; filament_cooling_moves = 4
; filament_cost = 25.4
; filament_density = 1.24
; filament_diameter = 1.75
; filament_load_time = 0
; filament_loading_speed = 28
; filament_loading_speed_start = 3
; filament_max_volumetric_speed = 15
; filament_minimal_purge_on_wipe_tower = 15
; filament_notes = ""
; filament_ramming_parameters = "120 100 6.6 6.8 7.2 7.6 7.9 8.2 8.7 9.4 9.9 10.0| 0.05 6.6 0.45 6.8 0.95 7.8 1.45 8.3 1.95 9.7 2.45 10 2.95 7.6 3.45 7.6 3.95 7.6 4.45 7.6 4.95 7.6"
; filament_settings_id = "Generic PLA"
; filament_soluble = 0
; filament_toolchange_delay = 0
; filament_type = PLA
; filament_unload_time = 0
; filament_unloading_speed = 90
; filament_unloading_speed_start = 100
; filament_vendor = Generic
; fill_angle = 45
; fill_density = 15%
; fill_pattern = gyroid
; first_layer_acceleration = 1000
; first_layer_bed_temperature = 60
; first_layer_extrusion_width = 0.42
; first_layer_height = 0.2
; first_layer_speed = 20
; first_layer_temperature = 215
; gap_fill_speed = 40
; gcode_comments = 0
; gcode_flavor = marlin
; gcode_label_objects = 0
; high_current_on_filament_swap = 0
; host_type = octoprint
; infill_acceleration = 1000
; infill_every_layers = 1
; infill_extruder = 1
; infill_extrusion_width = 0.45
; infill_first = 0
; infill_only_where_needed = 0
; infill_overlap = 25%
; infill_speed = 80
; interface_shells = 0
; layer_gcode = ;AFTER_LAYER_CHANGE\n;[layer_z]
; layer_height = 0.2
; machine_max_acceleration_e = 5000,5000
; machine_max_acceleration_extruding = 1250,1250
; machine_max_acceleration_retracting = 1250,1250
; machine_max_acceleration_x = 1000,960
; machine_max_acceleration_y = 1000,960
; machine_max_acceleration_z = 1000,1000
; machine_max_feedrate_e = 120,120
; machine_max_feedrate_x = 200,100
; machine_max_feedrate_y = 200,100
; machine_max_feedrate_z = 12,12
; machine_max_jerk_e = 4.5,4.5
; machine_max_jerk_x = 8,8
; machine_max_jerk_y = 8,8
; machine_max_jerk_z = 0.4,0.4
; machine_min_extruding_rate = 0,0
; machine_min_travel_rate = 0,0
; max_fan_speed = 100
; max_layer_height = 0.25
; max_print_height = 210
; max_print_speed = 200
; max_volumetric_speed = 0
; min_fan_speed = 100
; min_layer_height = 0.07
; min_print_speed = 15
; min_skirt_length = 4
; notes = 
; nozzle_diameter = 0.4
; only_retract_when_crossing_perimeters = 0
; ooze_prevention = 0
; output_filename_format = {input_filename_base}_{layer_height}mm_{filament_type[0]}_{printer_model}_{print_time}.gcode
; overhangs = 0
; parking_pos_retraction = 92
; perimeter_acceleration = 800
; perimeter_extruder = 1
; perimeter_extrusion_width = 0.45
; perimeter_speed = 45
; perimeters = 2
; post_process = 
; print_settings_id = 0.20mm QUALITY @MK3
; printer_model = MK3S
; printer_notes = Don't remove the following keywords! These keywords are used in the "compatible printer" condition of the print and filament profiles to link the particular print and filament profiles to this printer profile.\nPRINTER_VENDOR_PRUSA3D\nPRINTER_MODEL_MK3\n
; printer_settings_id = Original Prusa i3 MK3S
; printer_technology = FFF
; printer_variant = 0.4
; printer_vendor = 
; raft_layers = 0
; remaining_times = 1
; resolution = 0
; retract_before_travel = 1
; retract_before_wipe = 0%
; retract_layer_change = 1
; retract_length = 0.8
; retract_length_toolchange = 4
; retract_lift = 0.6
; retract_lift_above = 0
; retract_lift_below = 209
; retract_restart_extra = 0
; retract_restart_extra_toolchange = 0
; retract_speed = 35
; seam_position = nearest
; serial_port = 
; serial_speed = 250000
; silent_mode = 1
; single_extruder_multi_material = 0
; single_extruder_multi_material_priming = 0
; skirt_distance = 2
; skirt_height = 3
; skirts = 1
; slice_closing_radius = 0.049
; slowdown_below_layer_time = 20
; small_perimeter_speed = 25
; solid_infill_below_area = 0
; solid_infill_every_layers = 0
; solid_infill_extruder = 1
; solid_infill_extrusion_width = 0.45
; solid_infill_speed = 80
; spiral_vase = 0
; standby_temperature_delta = -5
; start_filament_gcode = "M900 K{if printer_notes=~/.*PRINTER_MODEL_MINI.*/ and nozzle_diameter[0]==0.6}0.12{elsif printer_notes=~/.*PRINTER_MODEL_MINI.*/}0.2{elsif printer_notes=~/.*PRINTER_HAS_BOWDEN.*/}200{elsif nozzle_diameter[0]==0.6}18{else}30{endif} ; Filament gcode"
; start_gcode = M862.3 P "[printer_model]" ; printer model check\nM862.1 P[nozzle_diameter] ; nozzle diameter check\nM115 U3.8.1 ; tell printer latest fw version\nG90 ; use absolute coordinates\nM83 ; extruder relative mode\nM104 S[first_layer_temperature] ; set extruder temp\nM140 S[first_layer_bed_temperature] ; set bed temp\nM190 S[first_layer_bed_temperature] ; wait for bed temp\nM109 S[first_layer_temperature] ; wait for extruder temp\nG28 W ; home all without mesh bed level\nG80 ; mesh bed leveling\nG1 Y-3.0 F1000.0 ; go outside print area\nG92 E0.0\nG1 X60.0 E9.0 F1000.0 ; intro line\nG1 X100.0 E12.5 F1000.0 ; intro line\nG92 E0.0\nM221 S{if layer_height<0.075}100{else}95{endif}
; support_material = 0
; support_material_angle = 0
; support_material_auto = 1
; support_material_buildplate_only = 0
; support_material_contact_distance = 0.1
; support_material_enforce_layers = 0
; support_material_extruder = 0
; support_material_extrusion_width = 0.35
; support_material_interface_contact_loops = 0
; support_material_interface_extruder = 0
; support_material_interface_layers = 2
; support_material_interface_spacing = 0.2
; support_material_interface_speed = 100%
; support_material_pattern = rectilinear
; support_material_spacing = 2
; support_material_speed = 50
; support_material_synchronize_layers = 0
; support_material_threshold = 55
; support_material_with_sheath = 0
; support_material_xy_spacing = 50%
; temperature = 210
; thin_walls = 0
; threads = 8
; thumbnails = 
; toolchange_gcode = 
; top_fill_pattern = rectilinear
; top_infill_extrusion_width = 0.4
; top_solid_infill_speed = 40
; top_solid_layers = 5
; top_solid_min_thickness = 0.6
; travel_speed = 180
; use_firmware_retraction = 0
; use_relative_e_distances = 1
; use_volumetric_e = 0
; variable_layer_height = 1
; wipe = 1
; wipe_into_infill = 0
; wipe_into_objects = 0
; wipe_tower = 1
; wipe_tower_bridging = 10
; wipe_tower_no_sparse_layers = 0
; wipe_tower_rotation_angle = 0
; wipe_tower_width = 60
; wipe_tower_x = 170
; wipe_tower_y = 125
; wiping_volumes_extruders = 70,70
; wiping_volumes_matrix = 0
; xy_size_compensation = 0
; z_offset = 0
