; generated by PrusaSlicer 2.2.0+ on 2020-05-18 at 01:48:55 UTC

; 

; external perimeters extrusion width = 0.45mm
; perimeters extrusion width = 0.45mm
; infill extrusion width = 0.45mm
; solid infill extrusion width = 0.45mm
; top infill extrusion width = 0.40mm
; first layer extrusion width = 0.42mm

M73 P0 R2
M73 Q0 S2
M201 X1000 Y1000 Z1000 E5000 ; sets maximum accelerations, mm/sec^2
M203 X200 Y200 Z12 E120 ; sets maximum feedrates, mm/sec
M204 P1250 R1250 T1250 ; sets acceleration (P, T) and retract acceleration (R), mm/sec^2
M205 X8.00 Y8.00 Z0.40 E4.50 ; sets the jerk limits, mm/sec
M205 S0 T0 ; sets the minimum extruding and travel feed rate, mm/sec
M107
M862.3 P "MK3S" ; printer model check
M862.1 P0.4 ; nozzle diameter check
M115 U3.8.1 ; tell printer latest fw version
G90 ; use absolute coordinates
M83 ; extruder relative mode
M104 S215 ; set extruder temp
M140 S60 ; set bed temp
M190 S60 ; wait for bed temp
M109 S215 ; wait for extruder temp
G28 W ; home all without mesh bed level
G80 ; mesh bed leveling
G1 Y-3.0 F1000.0 ; go outside print area
G92 E0.0
G1 X60.0 E9.0 F1000.0 ; intro line
M73 Q2 S2
M73 P2 R2
G1 X100.0 E12.5 F1000.0 ; intro line
G92 E0.0
M221 S95
G21 ; set units to millimeters
G90 ; use absolute coordinates
M83 ; use relative distances for extrusion
M900 K30 ; Filament gcode
;BEFORE_LAYER_CHANGE
G92 E0.0
;0.2


G1 E-0.80000 F2100.00000
G1 Z0.600 F10800.000
;AFTER_LAYER_CHANGE
;0.2
G1 X208.374 Y87.299
G1 Z0.200
G1 E0.80000 F2100.00000
M204 S1000
G1 F1200.000
G1 X209.293 Y87.090 E0.02954
G1 X239.355 Y87.089 E0.94257
G1 X240.236 Y87.260 E0.02813
G1 X240.988 Y87.742 E0.02802
G1 X241.510 Y88.472 E0.02813
G1 X241.725 Y89.343 E0.02813
G1 X241.728 Y119.512 E0.94592
G1 X241.555 Y120.358 E0.02708
G1 X241.093 Y121.084 E0.02696
G1 X240.307 Y121.643 E0.03024
G1 X239.360 Y121.843 E0.03036
G1 X209.302 Y121.843 E0.94245
G1 X208.459 Y121.670 E0.02696
G1 X207.734 Y121.208 E0.02696
G1 X207.173 Y120.419 E0.03036
G1 X206.974 Y119.475 E0.03024
G1 X206.975 Y89.417 E0.94245
G1 X207.148 Y88.574 E0.02696
G1 X207.609 Y87.849 E0.02696
G1 X208.325 Y87.334 E0.02766
G1 F8640.000
G1 X209.293 Y87.090 E-0.23038
G1 X211.587 Y87.090 E-0.52962
G1 E-0.04000 F2100.00000
G1 Z0.800 F10800.000
G1 X210.138 Y90.253
G1 Z0.200
G1 E0.80000 F2100.00000
G1 F1200.000
G1 X238.564 Y90.253 E0.89127
G1 X238.564 Y118.679 E0.89127
G1 X210.138 Y118.679 E0.89127
G1 X210.138 Y90.313 E0.88939
G1 X209.761 Y89.876 F10800.000
G1 F1200.000
G1 X238.941 Y89.876 E0.91492
G1 X238.941 Y119.056 E0.91492
G1 X209.761 Y119.056 E0.91492
G1 X209.761 Y89.936 E0.91304
G1 X210.147 Y89.980 F10800.000
G1 F8640.000
G1 X213.052 Y89.929 E-0.76000
G1 E-0.04000 F2100.00000
G1 Z0.800 F10800.000
G1 X238.451 Y91.135
G1 Z0.200
G1 E0.80000 F2100.00000
G1 F1200.000
G1 X237.851 Y90.536 E0.02681
G1 X237.314 Y90.536 E0.01701
G1 X238.281 Y91.504 E0.04327
G1 X238.281 Y92.041 E0.01701
G1 X236.776 Y90.536 E0.06733
G1 X236.238 Y90.536 E0.01701
G1 X238.281 Y92.579 E0.09138
G1 X238.281 Y93.117 E0.01701
G1 X235.700 Y90.536 E0.11544
G1 X235.162 Y90.536 E0.01701
G1 X238.281 Y93.655 E0.13949
G1 X238.281 Y94.193 E0.01701
G1 X234.624 Y90.536 E0.16355
G1 X234.086 Y90.536 E0.01701
G1 X238.281 Y94.731 E0.18760
G1 X238.281 Y95.269 E0.01701
G1 X233.549 Y90.536 E0.21165
G1 X233.011 Y90.536 E0.01701
G1 X238.281 Y95.806 E0.23571
G1 X238.281 Y96.344 E0.01701
G1 X232.473 Y90.536 E0.25976
G1 X231.935 Y90.536 E0.01701
G1 X238.281 Y96.882 E0.28382
G1 X238.281 Y97.420 E0.01701
G1 X231.397 Y90.536 E0.30787
G1 X230.859 Y90.536 E0.01701
G1 X238.281 Y97.958 E0.33192
G1 X238.281 Y98.496 E0.01701
G1 X230.321 Y90.536 E0.35598
G1 X229.784 Y90.536 E0.01701
G1 X238.281 Y99.034 E0.38003
G1 X238.281 Y99.571 E0.01701
G1 X229.246 Y90.536 E0.40409
G1 X228.708 Y90.536 E0.01701
G1 X238.281 Y100.109 E0.42814
G1 X238.281 Y100.647 E0.01701
G1 X228.170 Y90.536 E0.45220
G1 X227.632 Y90.536 E0.01701
G1 X238.281 Y101.185 E0.47625
G1 X238.281 Y101.723 E0.01701
G1 X227.094 Y90.536 E0.50030
G1 X226.557 Y90.536 E0.01701
G1 X238.281 Y102.261 E0.52436
G1 X238.281 Y102.799 E0.01701
G1 X226.019 Y90.536 E0.54841
G1 X225.481 Y90.536 E0.01701
G1 X238.281 Y103.336 E0.57247
G1 X238.281 Y103.874 E0.01701
G1 X224.943 Y90.536 E0.59652
G1 X224.405 Y90.536 E0.01701
G1 X238.281 Y104.412 E0.62057
G1 X238.281 Y104.950 E0.01701
G1 X223.867 Y90.536 E0.64463
G1 X223.329 Y90.536 E0.01701
G1 X238.281 Y105.488 E0.66868
G1 X238.281 Y106.026 E0.01701
G1 X222.792 Y90.536 E0.69274
G1 X222.254 Y90.536 E0.01701
G1 X238.281 Y106.564 E0.71679
G1 X238.281 Y107.101 E0.01701
G1 X221.716 Y90.536 E0.74085
G1 X221.178 Y90.536 E0.01701
G1 X238.281 Y107.639 E0.76490
G1 X238.281 Y108.177 E0.01701
G1 X220.640 Y90.536 E0.78895
G1 X220.102 Y90.536 E0.01701
G1 X238.281 Y108.715 E0.81301
G1 X238.281 Y109.253 E0.01701
G1 X219.564 Y90.536 E0.83706
G1 X219.027 Y90.536 E0.01701
G1 X238.281 Y109.791 E0.86112
G1 X238.281 Y110.328 E0.01701
G1 X218.489 Y90.536 E0.88517
G1 X217.951 Y90.536 E0.01701
G1 X238.281 Y110.866 E0.90922
G1 X238.281 Y111.404 E0.01701
G1 X217.413 Y90.536 E0.93328
G1 X216.875 Y90.536 E0.01701
G1 X238.281 Y111.942 E0.95733
G1 X238.281 Y112.480 E0.01701
G1 X216.337 Y90.536 E0.98139
G1 X215.799 Y90.536 E0.01701
G1 X238.281 Y113.018 E1.00544
G1 X238.281 Y113.556 E0.01701
G1 X215.262 Y90.536 E1.02950
M73 Q45 S1
M73 P45 R1
G1 X214.724 Y90.536 E0.01701
G1 X238.281 Y114.093 E1.05355
G1 X238.281 Y114.631 E0.01701
G1 X214.186 Y90.536 E1.07760
G1 X213.648 Y90.536 E0.01701
G1 X238.281 Y115.169 E1.10166
G1 X238.281 Y115.707 E0.01701
G1 X213.110 Y90.536 E1.12571
G1 X212.572 Y90.536 E0.01701
G1 X238.281 Y116.245 E1.14977
G1 X238.281 Y116.783 E0.01701
G1 X212.034 Y90.536 E1.17382
G1 X211.497 Y90.536 E0.01701
G1 X238.281 Y117.321 E1.19787
G1 X238.281 Y117.858 E0.01701
G1 X210.959 Y90.536 E1.22193
G1 X210.421 Y90.536 E0.01701
G1 X238.281 Y118.396 E1.24598
G1 X237.743 Y118.396 E0.01701
G1 X210.421 Y91.074 E1.22193
G1 X210.421 Y91.612 E0.01701
G1 X237.205 Y118.396 E1.19787
G1 X236.668 Y118.396 E0.01701
G1 X210.421 Y92.150 E1.17382
G1 X210.421 Y92.687 E0.01701
G1 X236.130 Y118.396 E1.14976
G1 X235.592 Y118.396 E0.01701
G1 X210.421 Y93.225 E1.12571
G1 X210.421 Y93.763 E0.01701
G1 X235.054 Y118.396 E1.10166
G1 X234.516 Y118.396 E0.01701
G1 X210.421 Y94.301 E1.07760
G1 X210.421 Y94.839 E0.01701
G1 X233.978 Y118.396 E1.05355
G1 X233.440 Y118.396 E0.01701
G1 X210.421 Y95.377 E1.02949
G1 X210.421 Y95.915 E0.01701
G1 X232.903 Y118.396 E1.00544
G1 X232.365 Y118.396 E0.01701
G1 X210.421 Y96.452 E0.98139
G1 X210.421 Y96.990 E0.01701
G1 X231.827 Y118.396 E0.95733
G1 X231.289 Y118.396 E0.01701
G1 X210.421 Y97.528 E0.93328
G1 X210.421 Y98.066 E0.01701
G1 X230.751 Y118.396 E0.90922
G1 X230.213 Y118.396 E0.01701
G1 X210.421 Y98.604 E0.88517
G1 X210.421 Y99.142 E0.01701
G1 X229.676 Y118.396 E0.86112
G1 X229.138 Y118.396 E0.01701
G1 X210.421 Y99.680 E0.83706
G1 X210.421 Y100.217 E0.01701
G1 X228.600 Y118.396 E0.81301
G1 X228.062 Y118.396 E0.01701
G1 X210.421 Y100.755 E0.78895
G1 X210.421 Y101.293 E0.01701
G1 X227.524 Y118.396 E0.76490
G1 X226.986 Y118.396 E0.01701
G1 X210.421 Y101.831 E0.74084
G1 X210.421 Y102.369 E0.01701
G1 X226.448 Y118.396 E0.71679
G1 X225.911 Y118.396 E0.01701
G1 X210.421 Y102.907 E0.69274
G1 X210.421 Y103.444 E0.01701
G1 X225.373 Y118.396 E0.66868
G1 X224.835 Y118.396 E0.01701
G1 X210.421 Y103.982 E0.64463
G1 X210.421 Y104.520 E0.01701
G1 X224.297 Y118.396 E0.62057
G1 X223.759 Y118.396 E0.01701
G1 X210.421 Y105.058 E0.59652
G1 X210.421 Y105.596 E0.01701
G1 X223.221 Y118.396 E0.57247
G1 X222.683 Y118.396 E0.01701
G1 X210.421 Y106.134 E0.54841
G1 X210.421 Y106.672 E0.01701
G1 X222.146 Y118.396 E0.52436
G1 X221.608 Y118.396 E0.01701
G1 X210.421 Y107.209 E0.50030
M73 Q88 S0
M73 P88 R0
G1 X210.421 Y107.747 E0.01701
G1 X221.070 Y118.396 E0.47625
G1 X220.532 Y118.396 E0.01701
G1 X210.421 Y108.285 E0.45219
G1 X210.421 Y108.823 E0.01701
G1 X219.994 Y118.396 E0.42814
G1 X219.456 Y118.396 E0.01701
G1 X210.421 Y109.361 E0.40409
G1 X210.421 Y109.899 E0.01701
G1 X218.918 Y118.396 E0.38003
G1 X218.381 Y118.396 E0.01701
G1 X210.421 Y110.437 E0.35598
G1 X210.421 Y110.974 E0.01701
G1 X217.843 Y118.396 E0.33192
G1 X217.305 Y118.396 E0.01701
G1 X210.421 Y111.512 E0.30787
G1 X210.421 Y112.050 E0.01701
G1 X216.767 Y118.396 E0.28382
G1 X216.229 Y118.396 E0.01701
G1 X210.421 Y112.588 E0.25976
G1 X210.421 Y113.126 E0.01701
G1 X215.691 Y118.396 E0.23571
G1 X215.154 Y118.396 E0.01701
G1 X210.421 Y113.664 E0.21165
G1 X210.421 Y114.202 E0.01701
G1 X214.616 Y118.396 E0.18760
G1 X214.078 Y118.396 E0.01701
G1 X210.421 Y114.739 E0.16354
G1 X210.421 Y115.277 E0.01701
G1 X213.540 Y118.396 E0.13949
G1 X213.002 Y118.396 E0.01701
G1 X210.421 Y115.815 E0.11544
G1 X210.421 Y116.353 E0.01701
G1 X212.464 Y118.396 E0.09138
G1 X211.926 Y118.396 E0.01701
G1 X210.421 Y116.891 E0.06733
G1 X210.421 Y117.429 E0.01701
G1 X211.389 Y118.396 E0.04327
G1 X210.851 Y118.396 E0.01701
G1 X210.251 Y117.797 E0.02681
G1 F8640.000;_WIPE
G1 X210.851 Y118.396 E-0.19575
G1 F8640.000;_WIPE
G1 X211.389 Y118.396 E-0.12419
G1 F8640.000;_WIPE
G1 X210.421 Y117.429 E-0.31597
G1 F8640.000;_WIPE
G1 X210.421 Y116.891 E-0.12409
G1 E-0.04000 F2100.00000
G1 Z0.800 F10800.000
; Filament-specific end gcode
G4 ; wait
M221 S100
M104 S0 ; turn off temperature
M140 S0 ; turn off heatbed
M107 ; turn off fan
G1 Z30.8 ; Move print head up
G1 X0 Y200 F3000 ; home X axis
M84 ; disable motors
M73 P100 R0
M73 Q100 S0
; filament used [mm] = 77.7
; filament used [cm3] = 0.2
; filament used [g] = 0.2
; filament cost = 0.0

; total filament used [g] = 0.2
; total filament cost = 0.0
; estimated printing time (normal mode) = 2m 19s
; estimated printing time (silent mode) = 2m 20s

; avoid_crossing_perimeters = 0
; bed_custom_model = 
; bed_custom_texture = 
; bed_shape = 0x0,250x0,250x210,0x210
; bed_temperature = 60
; before_layer_gcode = ;BEFORE_LAYER_CHANGE\nG92 E0.0\n;[layer_z]\n\n
; between_objects_gcode = 
; bottom_fill_pattern = rectilinear
; bottom_solid_layers = 4
; bottom_solid_min_thickness = 0.5
; bridge_acceleration = 1000
; bridge_angle = 0
; bridge_fan_speed = 100
; bridge_flow_ratio = 0.95
; bridge_speed = 30
; brim_width = 0
; clip_multipart_objects = 1
; compatible_printers_condition_cummulative = "printer_notes=~/.*PRINTER_VENDOR_PRUSA3D.*/ and printer_notes=~/.*PRINTER_MODEL_MK3.*/ and nozzle_diameter[0]==0.4";"! (printer_notes=~/.*PRINTER_VENDOR_PRUSA3D.*/ and printer_notes=~/.*PRINTER_MODEL_MK(2.5|3).*/ and single_extruder_multi_material)"
; complete_objects = 0
; cooling = 1
; cooling_tube_length = 5
; cooling_tube_retraction = 91.5
; default_acceleration = 1000
; default_filament_profile = "Prusament PLA"
; default_print_profile = 0.15mm QUALITY @MK3
; deretract_speed = 0
; disable_fan_first_layers = 1
; dont_support_bridges = 1
; draft_shield = 0
; duplicate_distance = 6
; elefant_foot_compensation = 0.2
; end_filament_gcode = "; Filament-specific end gcode"
; end_gcode = G4 ; wait\nM221 S100\nM104 S0 ; turn off temperature\nM140 S0 ; turn off heatbed\nM107 ; turn off fan\n{if layer_z < max_print_height}G1 Z{z_offset+min(layer_z+30, max_print_height)}{endif} ; Move print head up\nG1 X0 Y200 F3000 ; home X axis\nM84 ; disable motors
; ensure_vertical_shell_thickness = 1
; external_perimeter_extrusion_width = 0.45
; external_perimeter_speed = 25
; external_perimeters_first = 0
; extra_loading_move = -2
; extra_perimeters = 0
; extruder_clearance_height = 20
; extruder_clearance_radius = 45
; extruder_colour = ""
; extruder_offset = 0x0
; extrusion_axis = E
; extrusion_multiplier = 1
; extrusion_width = 0.45
; fan_always_on = 1
; fan_below_layer_time = 100
; filament_colour = #FF8000
; filament_cooling_final_speed = 3.4
; filament_cooling_initial_speed = 2.2
; filament_cooling_moves = 4
; filament_cost = 25.4
; filament_density = 1.24
; filament_diameter = 1.75
; filament_load_time = 0
; filament_loading_speed = 28
; filament_loading_speed_start = 3
; filament_max_volumetric_speed = 15
; filament_minimal_purge_on_wipe_tower = 15
; filament_notes = ""
; filament_ramming_parameters = "120 100 6.6 6.8 7.2 7.6 7.9 8.2 8.7 9.4 9.9 10.0| 0.05 6.6 0.45 6.8 0.95 7.8 1.45 8.3 1.95 9.7 2.45 10 2.95 7.6 3.45 7.6 3.95 7.6 4.45 7.6 4.95 7.6"
; filament_settings_id = "Generic PLA"
; filament_soluble = 0
; filament_toolchange_delay = 0
; filament_type = PLA
; filament_unload_time = 0
; filament_unloading_speed = 90
; filament_unloading_speed_start = 100
; filament_vendor = Generic
; fill_angle = 45
; fill_density = 15%
; fill_pattern = gyroid
; first_layer_acceleration = 1000
; first_layer_bed_temperature = 60
; first_layer_extrusion_width = 0.42
; first_layer_height = 0.2
; first_layer_speed = 20
; first_layer_temperature = 215
; gap_fill_speed = 40
; gcode_comments = 0
; gcode_flavor = marlin
; gcode_label_objects = 0
; high_current_on_filament_swap = 0
; host_type = octoprint
; infill_acceleration = 1000
; infill_every_layers = 1
; infill_extruder = 1
; infill_extrusion_width = 0.45
; infill_first = 0
; infill_only_where_needed = 0
; infill_overlap = 25%
; infill_speed = 80
; interface_shells = 0
; layer_gcode = ;AFTER_LAYER_CHANGE\n;[layer_z]
; layer_height = 0.2
; machine_max_acceleration_e = 5000,5000
; machine_max_acceleration_extruding = 1250,1250
; machine_max_acceleration_retracting = 1250,1250
; machine_max_acceleration_x = 1000,960
; machine_max_acceleration_y = 1000,960
; machine_max_acceleration_z = 1000,1000
; machine_max_feedrate_e = 120,120
; machine_max_feedrate_x = 200,100
; machine_max_feedrate_y = 200,100
; machine_max_feedrate_z = 12,12
; machine_max_jerk_e = 4.5,4.5
; machine_max_jerk_x = 8,8
; machine_max_jerk_y = 8,8
; machine_max_jerk_z = 0.4,0.4
; machine_min_extruding_rate = 0,0
; machine_min_travel_rate = 0,0
; max_fan_speed = 100
; max_layer_height = 0.25
; max_print_height = 210
; max_print_speed = 200
; max_volumetric_speed = 0
; min_fan_speed = 100
; min_layer_height = 0.07
; min_print_speed = 15
; min_skirt_length = 4
; notes = 
; nozzle_diameter = 0.4
; only_retract_when_crossing_perimeters = 0
; ooze_prevention = 0
; output_filename_format = {input_filename_base}_{layer_height}mm_{filament_type[0]}_{printer_model}_{print_time}.gcode
; overhangs = 0
; parking_pos_retraction = 92
; perimeter_acceleration = 800
; perimeter_extruder = 1
; perimeter_extrusion_width = 0.45
; perimeter_speed = 45
; perimeters = 2
; post_process = 
; print_settings_id = 0.20mm QUALITY @MK3
; printer_model = MK3S
; printer_notes = Don't remove the following keywords! These keywords are used in the "compatible printer" condition of the print and filament profiles to link the particular print and filament profiles to this printer profile.\nPRINTER_VENDOR_PRUSA3D\nPRINTER_MODEL_MK3\n
; printer_settings_id = Original Prusa i3 MK3S
; printer_technology = FFF
; printer_variant = 0.4
; printer_vendor = 
; raft_layers = 0
; remaining_times = 1
; resolution = 0
; retract_before_travel = 1
; retract_before_wipe = 0%
; retract_layer_change = 1
; retract_length = 0.8
; retract_length_toolchange = 4
; retract_lift = 0.6
; retract_lift_above = 0
; retract_lift_below = 209
; retract_restart_extra = 0
; retract_restart_extra_toolchange = 0
; retract_speed = 35
; seam_position = nearest
; serial_port = 
; serial_speed = 250000
; silent_mode = 1
; single_extruder_multi_material = 0
; single_extruder_multi_material_priming = 0
; skirt_distance = 2
; skirt_height = 3
; skirts = 1
; slice_closing_radius = 0.049
; slowdown_below_layer_time = 20
; small_perimeter_speed = 25
; solid_infill_below_area = 0
; solid_infill_every_layers = 0
; solid_infill_extruder = 1
; solid_infill_extrusion_width = 0.45
; solid_infill_speed = 80
; spiral_vase = 0
; standby_temperature_delta = -5
; start_filament_gcode = "M900 K{if printer_notes=~/.*PRINTER_MODEL_MINI.*/ and nozzle_diameter[0]==0.6}0.12{elsif printer_notes=~/.*PRINTER_MODEL_MINI.*/}0.2{elsif printer_notes=~/.*PRINTER_HAS_BOWDEN.*/}200{elsif nozzle_diameter[0]==0.6}18{else}30{endif} ; Filament gcode"
; start_gcode = M862.3 P "[printer_model]" ; printer model check\nM862.1 P[nozzle_diameter] ; nozzle diameter check\nM115 U3.8.1 ; tell printer latest fw version\nG90 ; use absolute coordinates\nM83 ; extruder relative mode\nM104 S[first_layer_temperature] ; set extruder temp\nM140 S[first_layer_bed_temperature] ; set bed temp\nM190 S[first_layer_bed_temperature] ; wait for bed temp\nM109 S[first_layer_temperature] ; wait for extruder temp\nG28 W ; home all without mesh bed level\nG80 ; mesh bed leveling\nG1 Y-3.0 F1000.0 ; go outside print area\nG92 E0.0\nG1 X60.0 E9.0 F1000.0 ; intro line\nG1 X100.0 E12.5 F1000.0 ; intro line\nG92 E0.0\nM221 S{if layer_height<0.075}100{else}95{endif}
; support_material = 0
; support_material_angle = 0
; support_material_auto = 1
; support_material_buildplate_only = 0
; support_material_contact_distance = 0.1
; support_material_enforce_layers = 0
; support_material_extruder = 0
; support_material_extrusion_width = 0.35
; support_material_interface_contact_loops = 0
; support_material_interface_extruder = 0
; support_material_interface_layers = 2
; support_material_interface_spacing = 0.2
; support_material_interface_speed = 100%
; support_material_pattern = rectilinear
; support_material_spacing = 2
; support_material_speed = 50
; support_material_synchronize_layers = 0
; support_material_threshold = 55
; support_material_with_sheath = 0
; support_material_xy_spacing = 50%
; temperature = 210
; thin_walls = 0
; threads = 8
; thumbnails = 
; toolchange_gcode = 
; top_fill_pattern = rectilinear
; top_infill_extrusion_width = 0.4
; top_solid_infill_speed = 40
; top_solid_layers = 5
; top_solid_min_thickness = 0.6
; travel_speed = 180
; use_firmware_retraction = 0
; use_relative_e_distances = 1
; use_volumetric_e = 0
; variable_layer_height = 1
; wipe = 1
; wipe_into_infill = 0
; wipe_into_objects = 0
; wipe_tower = 1
; wipe_tower_bridging = 10
; wipe_tower_no_sparse_layers = 0
; wipe_tower_rotation_angle = 0
; wipe_tower_width = 60
; wipe_tower_x = 170
; wipe_tower_y = 125
; wiping_volumes_extruders = 70,70
; wiping_volumes_matrix = 0
; xy_size_compensation = 0
; z_offset = 0
