; generated by PrusaSlicer 2.2.0+ on 2020-05-18 at 01:49:34 UTC

; 

; external perimeters extrusion width = 0.45mm
; perimeters extrusion width = 0.45mm
; infill extrusion width = 0.45mm
; solid infill extrusion width = 0.45mm
; top infill extrusion width = 0.40mm
; first layer extrusion width = 0.42mm

M73 P0 R2
M73 Q0 S2
M201 X1000 Y1000 Z1000 E5000 ; sets maximum accelerations, mm/sec^2
M203 X200 Y200 Z12 E120 ; sets maximum feedrates, mm/sec
M204 P1250 R1250 T1250 ; sets acceleration (P, T) and retract acceleration (R), mm/sec^2
M205 X8.00 Y8.00 Z0.40 E4.50 ; sets the jerk limits, mm/sec
M205 S0 T0 ; sets the minimum extruding and travel feed rate, mm/sec
M107
M862.3 P "MK3S" ; printer model check
M862.1 P0.4 ; nozzle diameter check
M115 U3.8.1 ; tell printer latest fw version
G90 ; use absolute coordinates
M83 ; extruder relative mode
M104 S215 ; set extruder temp
M140 S60 ; set bed temp
M190 S60 ; wait for bed temp
M109 S215 ; wait for extruder temp
G28 W ; home all without mesh bed level
G80 ; mesh bed leveling
G1 Y-3.0 F1000.0 ; go outside print area
G92 E0.0
G1 X60.0 E9.0 F1000.0 ; intro line
M73 Q2 S2
M73 P2 R2
G1 X100.0 E12.5 F1000.0 ; intro line
G92 E0.0
M221 S95
G21 ; set units to millimeters
G90 ; use absolute coordinates
M83 ; use relative distances for extrusion
M900 K30 ; Filament gcode
;BEFORE_LAYER_CHANGE
G92 E0.0
;0.2


G1 E-0.80000 F2100.00000
G1 Z0.600 F10800.000
;AFTER_LAYER_CHANGE
;0.2
G1 X108.174 Y172.870
G1 Z0.200
G1 E0.80000 F2100.00000
M204 S1000
G1 F1200.000
G1 X109.093 Y172.661 E0.02954
G1 X139.155 Y172.660 E0.94257
G1 X140.036 Y172.831 E0.02813
G1 X140.788 Y173.313 E0.02802
G1 X141.310 Y174.043 E0.02813
G1 X141.525 Y174.914 E0.02813
G1 X141.528 Y205.083 E0.94592
G1 X141.354 Y205.929 E0.02708
G1 X140.893 Y206.654 E0.02696
G1 X140.107 Y207.213 E0.03024
G1 X139.160 Y207.414 E0.03036
G1 X109.102 Y207.414 E0.94245
G1 X108.259 Y207.241 E0.02696
G1 X107.534 Y206.779 E0.02696
G1 X106.973 Y205.990 E0.03036
G1 X106.774 Y205.046 E0.03024
G1 X106.774 Y174.988 E0.94245
G1 X106.948 Y174.145 E0.02696
G1 X107.409 Y173.420 E0.02696
G1 X108.125 Y172.905 E0.02766
G1 F8640.000
G1 X109.093 Y172.661 E-0.23038
G1 X111.387 Y172.661 E-0.52962
G1 E-0.04000 F2100.00000
G1 Z0.800 F10800.000
G1 X109.938 Y175.824
G1 Z0.200
G1 E0.80000 F2100.00000
G1 F1200.000
G1 X138.364 Y175.824 E0.89127
G1 X138.364 Y204.250 E0.89127
G1 X109.938 Y204.250 E0.89127
G1 X109.938 Y175.884 E0.88939
G1 X109.561 Y175.447 F10800.000
G1 F1200.000
G1 X138.741 Y175.447 E0.91492
G1 X138.741 Y204.627 E0.91492
G1 X109.561 Y204.627 E0.91492
G1 X109.561 Y175.507 E0.91304
G1 X109.947 Y175.551 F10800.000
G1 F8640.000
G1 X112.852 Y175.500 E-0.76000
G1 E-0.04000 F2100.00000
G1 Z0.800 F10800.000
G1 X138.251 Y176.706
G1 Z0.200
G1 E0.80000 F2100.00000
G1 F1200.000
G1 X137.651 Y176.107 E0.02681
G1 X137.113 Y176.107 E0.01701
G1 X138.081 Y177.075 E0.04327
G1 X138.081 Y177.612 E0.01701
G1 X136.576 Y176.107 E0.06733
G1 X136.038 Y176.107 E0.01701
G1 X138.081 Y178.150 E0.09138
G1 X138.081 Y178.688 E0.01701
G1 X135.500 Y176.107 E0.11544
G1 X134.962 Y176.107 E0.01701
G1 X138.081 Y179.226 E0.13949
G1 X138.081 Y179.764 E0.01701
G1 X134.424 Y176.107 E0.16355
G1 X133.886 Y176.107 E0.01701
G1 X138.081 Y180.302 E0.18760
G1 X138.081 Y180.840 E0.01701
G1 X133.349 Y176.107 E0.21165
G1 X132.811 Y176.107 E0.01701
G1 X138.081 Y181.377 E0.23571
G1 X138.081 Y181.915 E0.01701
G1 X132.273 Y176.107 E0.25976
G1 X131.735 Y176.107 E0.01701
G1 X138.081 Y182.453 E0.28382
G1 X138.081 Y182.991 E0.01701
G1 X131.197 Y176.107 E0.30787
G1 X130.659 Y176.107 E0.01701
G1 X138.081 Y183.529 E0.33192
G1 X138.081 Y184.067 E0.01701
G1 X130.121 Y176.107 E0.35598
G1 X129.584 Y176.107 E0.01701
G1 X138.081 Y184.605 E0.38003
G1 X138.081 Y185.142 E0.01701
G1 X129.046 Y176.107 E0.40409
G1 X128.508 Y176.107 E0.01701
G1 X138.081 Y185.680 E0.42814
G1 X138.081 Y186.218 E0.01701
G1 X127.970 Y176.107 E0.45220
G1 X127.432 Y176.107 E0.01701
G1 X138.081 Y186.756 E0.47625
G1 X138.081 Y187.294 E0.01701
G1 X126.894 Y176.107 E0.50030
G1 X126.356 Y176.107 E0.01701
G1 X138.081 Y187.832 E0.52436
G1 X138.081 Y188.369 E0.01701
G1 X125.819 Y176.107 E0.54841
G1 X125.281 Y176.107 E0.01701
G1 X138.081 Y188.907 E0.57247
G1 X138.081 Y189.445 E0.01701
G1 X124.743 Y176.107 E0.59652
G1 X124.205 Y176.107 E0.01701
G1 X138.081 Y189.983 E0.62057
G1 X138.081 Y190.521 E0.01701
G1 X123.667 Y176.107 E0.64463
G1 X123.129 Y176.107 E0.01701
G1 X138.081 Y191.059 E0.66868
G1 X138.081 Y191.597 E0.01701
G1 X122.591 Y176.107 E0.69274
G1 X122.054 Y176.107 E0.01701
G1 X138.081 Y192.134 E0.71679
G1 X138.081 Y192.672 E0.01701
G1 X121.516 Y176.107 E0.74085
G1 X120.978 Y176.107 E0.01701
G1 X138.081 Y193.210 E0.76490
G1 X138.081 Y193.748 E0.01701
G1 X120.440 Y176.107 E0.78895
G1 X119.902 Y176.107 E0.01701
G1 X138.081 Y194.286 E0.81301
G1 X138.081 Y194.824 E0.01701
G1 X119.364 Y176.107 E0.83706
G1 X118.827 Y176.107 E0.01701
G1 X138.081 Y195.362 E0.86112
G1 X138.081 Y195.899 E0.01701
G1 X118.289 Y176.107 E0.88517
G1 X117.751 Y176.107 E0.01701
G1 X138.081 Y196.437 E0.90922
G1 X138.081 Y196.975 E0.01701
G1 X117.213 Y176.107 E0.93328
G1 X116.675 Y176.107 E0.01701
G1 X138.081 Y197.513 E0.95733
G1 X138.081 Y198.051 E0.01701
G1 X116.137 Y176.107 E0.98139
G1 X115.599 Y176.107 E0.01701
G1 X138.081 Y198.589 E1.00544
G1 X138.081 Y199.127 E0.01701
G1 X115.062 Y176.107 E1.02950
M73 Q46 S1
M73 P46 R1
G1 X114.524 Y176.107 E0.01701
G1 X138.081 Y199.664 E1.05355
G1 X138.081 Y200.202 E0.01701
G1 X113.986 Y176.107 E1.07760
G1 X113.448 Y176.107 E0.01701
G1 X138.081 Y200.740 E1.10166
G1 X138.081 Y201.278 E0.01701
G1 X112.910 Y176.107 E1.12571
G1 X112.372 Y176.107 E0.01701
G1 X138.081 Y201.816 E1.14977
G1 X138.081 Y202.354 E0.01701
G1 X111.834 Y176.107 E1.17382
G1 X111.297 Y176.107 E0.01701
G1 X138.081 Y202.891 E1.19787
G1 X138.081 Y203.429 E0.01701
G1 X110.759 Y176.107 E1.22193
G1 X110.221 Y176.107 E0.01701
G1 X138.081 Y203.967 E1.24598
G1 X137.543 Y203.967 E0.01701
G1 X110.221 Y176.645 E1.22193
G1 X110.221 Y177.183 E0.01701
G1 X137.005 Y203.967 E1.19787
G1 X136.468 Y203.967 E0.01701
G1 X110.221 Y177.721 E1.17382
G1 X110.221 Y178.258 E0.01701
G1 X135.930 Y203.967 E1.14976
G1 X135.392 Y203.967 E0.01701
G1 X110.221 Y178.796 E1.12571
G1 X110.221 Y179.334 E0.01701
G1 X134.854 Y203.967 E1.10166
G1 X134.316 Y203.967 E0.01701
G1 X110.221 Y179.872 E1.07760
G1 X110.221 Y180.410 E0.01701
G1 X133.778 Y203.967 E1.05355
G1 X133.240 Y203.967 E0.01701
G1 X110.221 Y180.948 E1.02949
G1 X110.221 Y181.485 E0.01701
G1 X132.703 Y203.967 E1.00544
G1 X132.165 Y203.967 E0.01701
G1 X110.221 Y182.023 E0.98139
G1 X110.221 Y182.561 E0.01701
G1 X131.627 Y203.967 E0.95733
G1 X131.089 Y203.967 E0.01701
G1 X110.221 Y183.099 E0.93328
G1 X110.221 Y183.637 E0.01701
G1 X130.551 Y203.967 E0.90922
G1 X130.013 Y203.967 E0.01701
G1 X110.221 Y184.175 E0.88517
G1 X110.221 Y184.713 E0.01701
G1 X129.475 Y203.967 E0.86112
G1 X128.938 Y203.967 E0.01701
G1 X110.221 Y185.250 E0.83706
G1 X110.221 Y185.788 E0.01701
G1 X128.400 Y203.967 E0.81301
G1 X127.862 Y203.967 E0.01701
G1 X110.221 Y186.326 E0.78895
G1 X110.221 Y186.864 E0.01701
G1 X127.324 Y203.967 E0.76490
G1 X126.786 Y203.967 E0.01701
G1 X110.221 Y187.402 E0.74084
G1 X110.221 Y187.940 E0.01701
G1 X126.248 Y203.967 E0.71679
G1 X125.711 Y203.967 E0.01701
G1 X110.221 Y188.478 E0.69274
G1 X110.221 Y189.015 E0.01701
G1 X125.173 Y203.967 E0.66868
G1 X124.635 Y203.967 E0.01701
G1 X110.221 Y189.553 E0.64463
G1 X110.221 Y190.091 E0.01701
G1 X124.097 Y203.967 E0.62057
G1 X123.559 Y203.967 E0.01701
G1 X110.221 Y190.629 E0.59652
G1 X110.221 Y191.167 E0.01701
G1 X123.021 Y203.967 E0.57247
G1 X122.483 Y203.967 E0.01701
G1 X110.221 Y191.705 E0.54841
G1 X110.221 Y192.243 E0.01701
G1 X121.946 Y203.967 E0.52436
G1 X121.408 Y203.967 E0.01701
G1 X110.221 Y192.780 E0.50030
M73 Q90 S0
M73 P90 R0
G1 X110.221 Y193.318 E0.01701
G1 X120.870 Y203.967 E0.47625
G1 X120.332 Y203.967 E0.01701
G1 X110.221 Y193.856 E0.45219
G1 X110.221 Y194.394 E0.01701
G1 X119.794 Y203.967 E0.42814
G1 X119.256 Y203.967 E0.01701
G1 X110.221 Y194.932 E0.40409
G1 X110.221 Y195.470 E0.01701
G1 X118.718 Y203.967 E0.38003
G1 X118.181 Y203.967 E0.01701
G1 X110.221 Y196.007 E0.35598
G1 X110.221 Y196.545 E0.01701
G1 X117.643 Y203.967 E0.33192
G1 X117.105 Y203.967 E0.01701
G1 X110.221 Y197.083 E0.30787
G1 X110.221 Y197.621 E0.01701
G1 X116.567 Y203.967 E0.28382
G1 X116.029 Y203.967 E0.01701
G1 X110.221 Y198.159 E0.25976
G1 X110.221 Y198.697 E0.01701
G1 X115.491 Y203.967 E0.23571
G1 X114.953 Y203.967 E0.01701
G1 X110.221 Y199.235 E0.21165
G1 X110.221 Y199.772 E0.01701
G1 X114.416 Y203.967 E0.18760
G1 X113.878 Y203.967 E0.01701
G1 X110.221 Y200.310 E0.16354
G1 X110.221 Y200.848 E0.01701
G1 X113.340 Y203.967 E0.13949
G1 X112.802 Y203.967 E0.01701
G1 X110.221 Y201.386 E0.11544
G1 X110.221 Y201.924 E0.01701
G1 X112.264 Y203.967 E0.09138
G1 X111.726 Y203.967 E0.01701
G1 X110.221 Y202.462 E0.06733
G1 X110.221 Y203.000 E0.01701
G1 X111.189 Y203.967 E0.04327
G1 X110.651 Y203.967 E0.01701
G1 X110.051 Y203.368 E0.02681
G1 F8640.000;_WIPE
G1 X110.651 Y203.967 E-0.19575
G1 F8640.000;_WIPE
G1 X111.189 Y203.967 E-0.12419
G1 F8640.000;_WIPE
G1 X110.221 Y203.000 E-0.31597
G1 F8640.000;_WIPE
G1 X110.221 Y202.462 E-0.12409
G1 E-0.04000 F2100.00000
G1 Z0.800 F10800.000
; Filament-specific end gcode
G4 ; wait
M221 S100
M104 S0 ; turn off temperature
M140 S0 ; turn off heatbed
M107 ; turn off fan
G1 Z30.8 ; Move print head up
G1 X0 Y200 F3000 ; home X axis
M84 ; disable motors
M73 P100 R0
M73 Q100 S0
; filament used [mm] = 77.7
; filament used [cm3] = 0.2
; filament used [g] = 0.2
; filament cost = 0.0

; total filament used [g] = 0.2
; total filament cost = 0.0
; estimated printing time (normal mode) = 2m 17s
; estimated printing time (silent mode) = 2m 18s

; avoid_crossing_perimeters = 0
; bed_custom_model = 
; bed_custom_texture = 
; bed_shape = 0x0,250x0,250x210,0x210
; bed_temperature = 60
; before_layer_gcode = ;BEFORE_LAYER_CHANGE\nG92 E0.0\n;[layer_z]\n\n
; between_objects_gcode = 
; bottom_fill_pattern = rectilinear
; bottom_solid_layers = 4
; bottom_solid_min_thickness = 0.5
; bridge_acceleration = 1000
; bridge_angle = 0
; bridge_fan_speed = 100
; bridge_flow_ratio = 0.95
; bridge_speed = 30
; brim_width = 0
; clip_multipart_objects = 1
; compatible_printers_condition_cummulative = "printer_notes=~/.*PRINTER_VENDOR_PRUSA3D.*/ and printer_notes=~/.*PRINTER_MODEL_MK3.*/ and nozzle_diameter[0]==0.4";"! (printer_notes=~/.*PRINTER_VENDOR_PRUSA3D.*/ and printer_notes=~/.*PRINTER_MODEL_MK(2.5|3).*/ and single_extruder_multi_material)"
; complete_objects = 0
; cooling = 1
; cooling_tube_length = 5
; cooling_tube_retraction = 91.5
; default_acceleration = 1000
; default_filament_profile = "Prusament PLA"
; default_print_profile = 0.15mm QUALITY @MK3
; deretract_speed = 0
; disable_fan_first_layers = 1
; dont_support_bridges = 1
; draft_shield = 0
; duplicate_distance = 6
; elefant_foot_compensation = 0.2
; end_filament_gcode = "; Filament-specific end gcode"
; end_gcode = G4 ; wait\nM221 S100\nM104 S0 ; turn off temperature\nM140 S0 ; turn off heatbed\nM107 ; turn off fan\n{if layer_z < max_print_height}G1 Z{z_offset+min(layer_z+30, max_print_height)}{endif} ; Move print head up\nG1 X0 Y200 F3000 ; home X axis\nM84 ; disable motors
; ensure_vertical_shell_thickness = 1
; external_perimeter_extrusion_width = 0.45
; external_perimeter_speed = 25
; external_perimeters_first = 0
; extra_loading_move = -2
; extra_perimeters = 0
; extruder_clearance_height = 20
; extruder_clearance_radius = 45
; extruder_colour = ""
; extruder_offset = 0x0
; extrusion_axis = E
; extrusion_multiplier = 1
; extrusion_width = 0.45
; fan_always_on = 1
; fan_below_layer_time = 100
; filament_colour = #FF8000
; filament_cooling_final_speed = 3.4
; filament_cooling_initial_speed = 2.2
; filament_cooling_moves = 4
; filament_cost = 25.4
; filament_density = 1.24
; filament_diameter = 1.75
; filament_load_time = 0
; filament_loading_speed = 28
; filament_loading_speed_start = 3
; filament_max_volumetric_speed = 15
; filament_minimal_purge_on_wipe_tower = 15
; filament_notes = ""
; filament_ramming_parameters = "120 100 6.6 6.8 7.2 7.6 7.9 8.2 8.7 9.4 9.9 10.0| 0.05 6.6 0.45 6.8 0.95 7.8 1.45 8.3 1.95 9.7 2.45 10 2.95 7.6 3.45 7.6 3.95 7.6 4.45 7.6 4.95 7.6"
; filament_settings_id = "Generic PLA"
; filament_soluble = 0
; filament_toolchange_delay = 0
; filament_type = PLA
; filament_unload_time = 0
; filament_unloading_speed = 90
; filament_unloading_speed_start = 100
; filament_vendor = Generic
; fill_angle = 45
; fill_density = 15%
; fill_pattern = gyroid
; first_layer_acceleration = 1000
; first_layer_bed_temperature = 60
; first_layer_extrusion_width = 0.42
; first_layer_height = 0.2
; first_layer_speed = 20
; first_layer_temperature = 215
; gap_fill_speed = 40
; gcode_comments = 0
; gcode_flavor = marlin
; gcode_label_objects = 0
; high_current_on_filament_swap = 0
; host_type = octoprint
; infill_acceleration = 1000
; infill_every_layers = 1
; infill_extruder = 1
; infill_extrusion_width = 0.45
; infill_first = 0
; infill_only_where_needed = 0
; infill_overlap = 25%
; infill_speed = 80
; interface_shells = 0
; layer_gcode = ;AFTER_LAYER_CHANGE\n;[layer_z]
; layer_height = 0.2
; machine_max_acceleration_e = 5000,5000
; machine_max_acceleration_extruding = 1250,1250
; machine_max_acceleration_retracting = 1250,1250
; machine_max_acceleration_x = 1000,960
; machine_max_acceleration_y = 1000,960
; machine_max_acceleration_z = 1000,1000
; machine_max_feedrate_e = 120,120
; machine_max_feedrate_x = 200,100
; machine_max_feedrate_y = 200,100
; machine_max_feedrate_z = 12,12
; machine_max_jerk_e = 4.5,4.5
; machine_max_jerk_x = 8,8
; machine_max_jerk_y = 8,8
; machine_max_jerk_z = 0.4,0.4
; machine_min_extruding_rate = 0,0
; machine_min_travel_rate = 0,0
; max_fan_speed = 100
; max_layer_height = 0.25
; max_print_height = 210
; max_print_speed = 200
; max_volumetric_speed = 0
; min_fan_speed = 100
; min_layer_height = 0.07
; min_print_speed = 15
; min_skirt_length = 4
; notes = 
; nozzle_diameter = 0.4
; only_retract_when_crossing_perimeters = 0
; ooze_prevention = 0
; output_filename_format = {input_filename_base}_{layer_height}mm_{filament_type[0]}_{printer_model}_{print_time}.gcode
; overhangs = 0
; parking_pos_retraction = 92
; perimeter_acceleration = 800
; perimeter_extruder = 1
; perimeter_extrusion_width = 0.45
; perimeter_speed = 45
; perimeters = 2
; post_process = 
; print_settings_id = 0.20mm QUALITY @MK3
; printer_model = MK3S
; printer_notes = Don't remove the following keywords! These keywords are used in the "compatible printer" condition of the print and filament profiles to link the particular print and filament profiles to this printer profile.\nPRINTER_VENDOR_PRUSA3D\nPRINTER_MODEL_MK3\n
; printer_settings_id = Original Prusa i3 MK3S
; printer_technology = FFF
; printer_variant = 0.4
; printer_vendor = 
; raft_layers = 0
; remaining_times = 1
; resolution = 0
; retract_before_travel = 1
; retract_before_wipe = 0%
; retract_layer_change = 1
; retract_length = 0.8
; retract_length_toolchange = 4
; retract_lift = 0.6
; retract_lift_above = 0
; retract_lift_below = 209
; retract_restart_extra = 0
; retract_restart_extra_toolchange = 0
; retract_speed = 35
; seam_position = nearest
; serial_port = 
; serial_speed = 250000
; silent_mode = 1
; single_extruder_multi_material = 0
; single_extruder_multi_material_priming = 0
; skirt_distance = 2
; skirt_height = 3
; skirts = 1
; slice_closing_radius = 0.049
; slowdown_below_layer_time = 20
; small_perimeter_speed = 25
; solid_infill_below_area = 0
; solid_infill_every_layers = 0
; solid_infill_extruder = 1
; solid_infill_extrusion_width = 0.45
; solid_infill_speed = 80
; spiral_vase = 0
; standby_temperature_delta = -5
; start_filament_gcode = "M900 K{if printer_notes=~/.*PRINTER_MODEL_MINI.*/ and nozzle_diameter[0]==0.6}0.12{elsif printer_notes=~/.*PRINTER_MODEL_MINI.*/}0.2{elsif printer_notes=~/.*PRINTER_HAS_BOWDEN.*/}200{elsif nozzle_diameter[0]==0.6}18{else}30{endif} ; Filament gcode"
; start_gcode = M862.3 P "[printer_model]" ; printer model check\nM862.1 P[nozzle_diameter] ; nozzle diameter check\nM115 U3.8.1 ; tell printer latest fw version\nG90 ; use absolute coordinates\nM83 ; extruder relative mode\nM104 S[first_layer_temperature] ; set extruder temp\nM140 S[first_layer_bed_temperature] ; set bed temp\nM190 S[first_layer_bed_temperature] ; wait for bed temp\nM109 S[first_layer_temperature] ; wait for extruder temp\nG28 W ; home all without mesh bed level\nG80 ; mesh bed leveling\nG1 Y-3.0 F1000.0 ; go outside print area\nG92 E0.0\nG1 X60.0 E9.0 F1000.0 ; intro line\nG1 X100.0 E12.5 F1000.0 ; intro line\nG92 E0.0\nM221 S{if layer_height<0.075}100{else}95{endif}
; support_material = 0
; support_material_angle = 0
; support_material_auto = 1
; support_material_buildplate_only = 0
; support_material_contact_distance = 0.1
; support_material_enforce_layers = 0
; support_material_extruder = 0
; support_material_extrusion_width = 0.35
; support_material_interface_contact_loops = 0
; support_material_interface_extruder = 0
; support_material_interface_layers = 2
; support_material_interface_spacing = 0.2
; support_material_interface_speed = 100%
; support_material_pattern = rectilinear
; support_material_spacing = 2
; support_material_speed = 50
; support_material_synchronize_layers = 0
; support_material_threshold = 55
; support_material_with_sheath = 0
; support_material_xy_spacing = 50%
; temperature = 210
; thin_walls = 0
; threads = 8
; thumbnails = 
; toolchange_gcode = 
; top_fill_pattern = rectilinear
; top_infill_extrusion_width = 0.4
; top_solid_infill_speed = 40
; top_solid_layers = 5
; top_solid_min_thickness = 0.6
; travel_speed = 180
; use_firmware_retraction = 0
; use_relative_e_distances = 1
; use_volumetric_e = 0
; variable_layer_height = 1
; wipe = 1
; wipe_into_infill = 0
; wipe_into_objects = 0
; wipe_tower = 1
; wipe_tower_bridging = 10
; wipe_tower_no_sparse_layers = 0
; wipe_tower_rotation_angle = 0
; wipe_tower_width = 60
; wipe_tower_x = 170
; wipe_tower_y = 125
; wiping_volumes_extruders = 70,70
; wiping_volumes_matrix = 0
; xy_size_compensation = 0
; z_offset = 0
